config/routes.rb
Rails.application.routes.draw do
  # get "player_mypages/index"
  root "top#index"
  # get "player_mypages/index" => "player_mypages#index"
  devise_for :players
  devise_for :teams
  resource :player_mypages
  get "players/:id" => "players#show"
  resource :team_mypages
  get "teams/:id" => "teams#show"
  get "player_profile/show" => "player_profile#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/player_schedule.rb
class PlayerSchedule < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/team_schedule.rb
class TeamSchedule < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    if resource.instance_of?(Player)
      player_mypages_path(resource)
    elsif resource.instance_of?(Team)
      team_mypages_path(resource)
    end
  end
end

app/controllers/player_mypages_controller.rb
class PlayerMypagesController < ApplicationController
  before_action :authenticate_player!

  def show
    flash[:notice] = "ログイン済ユーザーのみ記事の詳細を確認できます" unless player_signed_in?
  end
end

app/controllers/player_profile_controller.rb
class PlayerProfileController < ApplicationController

  def show

  end
  
end

app/controllers/players/application_controller.rb
class Players::ApplicationController < ApplicationController
  layout "layouts/application"
  before_action :authenticate_player!

  def show
  end

  def after_sign_in_path_for(resource)
    player_mypages(resource.id)
  end

  def after_sign_in_path_for(resource)
    team_mypages(resource.id)
  end
end

app/controllers/team_mypages_controller.rb
class TeamMypagesController < ApplicationController
  before_action :authenticate_team!

  def show
    flash[:notice] = "ログイン済ユーザーのみ記事の詳細を確認できます" unless team_signed_in?
    # ********** 以下を追加 **********
    gon.chart_label = ["1/1", "1/2", "1/4", "1/5", "1/6", "1/7"]
    # null を nil にしないといけないので注意！
    gon.chart_data = [60.3, 61.1, 60.8, nil, 60.5, 61.4]
    # ********** 以上を追加 **********
  end
end

app/controllers/teams/application_controller.rb
class Teams::ApplicationController < ApplicationController
  layout "layouts/application"
  before_action :authenticate_team!
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mypage_p_helper.rb
module MypagePHelper
end

app/helpers/player_profile_helper.rb
module PlayerProfileHelper
end

app/helpers/team_mypages_helper.rb
module TeamMypagesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/_header.html.erb
<p>このアプリについて</p>
<a href="https://www.windy.com/26.210/127.690?rain,2020-09-13-06,20.335,124.885,6">お天気</a>
<% if player_signed_in? %>
  <%= link_to "アカウント編集", edit_player_registration_path %>
  <%= link_to "ログアウト", destroy_player_session_path, method: :delete %>
  <%= "【ログイン中のアドレス】#{current_player.email}" %>
<% else %>
  <%= link_to "プレーヤー登録", new_player_registration_path %>
  <%= link_to "ログイン", new_player_session_path %>
<% end %>
<% if team_signed_in? %>
  <%= link_to "アカウント編集", edit_team_registration_path %>
  <%= link_to "ログアウト", destroy_team_session_path, method: :delete %>
  <%= "【ログイン中のアドレス】#{current_team.email}" %>
<% else %>
  <%= link_to "チーム登録", new_team_registration_path %>
  <%= link_to "ログイン", new_team_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkettoSearchApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/player_mypages/show.html.erb
<nav class="navbar navbar-light bg-light fixed-top">
  <a class="navbar-brand mr-auto" href="#">チーム名</a>
  <div class="input-group" style="width: auto;">
    <input type="text" class="form-control" placeholder="テキスト入力欄">
    <span class="input-group-btn">
      <button class="btn btn-default" type="submit">
        <i class="fas fa-search"></i> 検索
      </button>
    </span>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#" aria-controls="#" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="#">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">TOP</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">通知</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">メール</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">天気</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">一覧</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">アカウント編集</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
    </ul>
  </div>
</nav>
<form class="form-inline">
  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
</nav>
<div id="calendar-container">
  <div class="left-item">
    <a href="#">通知</a><br>
    <a href="#">メール</a><br>
    <a href="#">天気</a><br>
    <a href="#">一覧</a><br>
    <a href="#">アカウント編集</a>
  </div>
  <div class="right-item">
    <div id="calendar" class="calendar"></div>
  </div>
</div>

app/views/player_profile/show.html.erb
<%= Gon::Base.render_data %>
<div class="header">
  <p><img src='/img/img24x24.png' alt='' style="width:24px;height:24px;vertical-align:middle;"><span style="vertical-align:middle;">abc</span></p>
</div>

app/views/players/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/players/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t(".sign_in"), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t(".sign_up"), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t(".forgot_your_password"), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t('.sign_in_with_provider', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/team_mypages/show.html.erb
<%= Gon::Base.render_data %>
<nav class="navbar navbar-light bg-light fixed-top">
  <a class="navbar-brand mr-auto" href="#">チーム名</a>
  <div class="input-group" style="width: auto;">
    <input type="text" class="form-control" placeholder="テキスト入力欄">
    <span class="input-group-btn">
      <button class="btn btn-default" type="submit">
        <i class="fas fa-search"></i> 検索
      </button>
    </span>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#" aria-controls="#" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="#">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">TOP</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">通知</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">メール</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">天気</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">一覧</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">アカウント編集</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
    </ul>
  </div>
</nav>
<form class="form-inline">
  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
</nav>
<div id="calendar-container">
  <div class="left-item">
    <a href="#">通知</a><br>
    <a href="#">メール</a><br>
    <a href="#">天気</a><br>
    <a href="#">一覧</a><br>
    <a href="#">アカウント編集</a>
  </div>
  <div class="right-item">
    <div id="calendar" class="calendar"></div>
  </div>
</div>

app/views/top/index.html.erb
<a href="https://www.windy.com/?25.607,128.102,8">お天気</a>
<% if player_signed_in? %>
  <%= link_to "アカウント編集", edit_player_registration_path %>
  <%= link_to "ログアウト", destroy_player_session_path, method: :delete %>
  <%= "【ログイン中のアドレス】#{current_player.email}" %>
<% else %>
  <%= link_to "プレイヤーログイン", new_player_session_path %>
<% end %>
<% if team_signed_in? %>
  <%= link_to "アカウント編集", edit_team_registration_path %>
  <%= link_to "ログアウト", destroy_team_session_path, method: :delete %>
  <%= "【ログイン中のアドレス】#{current_team.email}" %>
<% else %>
  <%= link_to "チームログイン", new_team_session_path %>
<% end %>
<hr>
<h1>野球しようよ！！</h1>
<h3>〜全てのスポーツマン＆ウーマンの為に〜</h3>
<p>球場やコートを抑えたけど人数不足で困っているチームや監督さん、
  また、所属チームで試合が無くスポーツがしたくてウズウズしているプレイヤーさん、
  私の周りではそのようなチームやプレイヤーがたくさんいます！
  そのような互いに互いを必要としている人達の助けになるようなアプリが開発できればなと
  この助っ人サーチ（仮）を開発することにしました。
</p>
<h3>チーム</h3>
<i class="fab fa-facebook"></i>
<i class="fab fa-twitter-square"></i>
<%= link_to new_team_registration_path do %>
  <i class="far fa-envelope"></i>メール
<% end %>
<h3>プレイヤー</h3>
<i class="fab fa-facebook"></i>
<i class="fab fa-twitter-square"></i>
<%= link_to new_player_registration_path do %>
  <i class="far fa-envelope"></i>メール
<% end %>